backend:
  - changed-files:
    - any-glob-to-any-file: 'backend/**'

frontend:
  - changed-files:
    - any-glob-to-any-file: 'static/js/**'

tests:
  - changed-files:
    - any-glob-to-any-file: 'tests/**'

docker:
  - changed-files:
    - any-glob-to-any-file:
      - 'Dockerfile'
      - 'docker-compose.yml'

documentation:
  - changed-files:
    - any-glob-to-any-file: '*.md'
