"""GraphQL queries for Wiz API integration."""

from .queries import (
    CLOUD_ACCOUNTS_QUERY,
    CLOUD_CONFIG_RULES_QUERY,
    CONFIG_FINDINGS_QUERY,
    DATA_FINDINGS_QUERY,
    EXCESSIVE_ACCESS_QUERY,
    HOST_CONFIG_QUERY,
    INVENTORY_FINDINGS_QUERY,
    ISSUES_QUERY,
    NETWORK_EXPOSURE_QUERY,
    PROJECTS_QUERY,
    QUERY_TYPE_MAP,
    SCHEMA_INTROSPECTION_QUERY,
    SECRET_INSTANCES_QUERY,
    VULN_FINDINGS_QUERY,
)

__all__ = [
    "ISSUES_QUERY",
    "CONFIG_FINDINGS_QUERY",
    "VULN_FINDINGS_QUERY",
    "HOST_CONFIG_QUERY",
    "DATA_FINDINGS_QUERY",
    "SECRET_INSTANCES_QUERY",
    "EXCESSIVE_ACCESS_QUERY",
    "NETWORK_EXPOSURE_QUERY",
    "INVENTORY_FINDINGS_QUERY",
    "PROJECTS_QUERY",
    "CLOUD_ACCOUNTS_QUERY",
    "CLOUD_CONFIG_RULES_QUERY",
    "SCHEMA_INTROSPECTION_QUERY",
    "QUERY_TYPE_MAP",
]
